### ISSUE TITLE
Code generation does not work well with the OpenAPI 2.0

### ISSUE THREAD

**Issue by biancode** [mimosa-org/ws-isbm#2]
Hi,

I tested with the Editor to generate a server and client from the OpenAPI of version 2.0 from the complete file via
https://editor.swagger.io/ - but it produced a lot of errors in the code-generations. (tested with node server/client)

![image](https://user-images.githubusercontent.com/4369867/92994246-12f06580-f4f9-11ea-9e92-87c5ef9e04e3.png)

Was the 2.0 tested to generate well for clients and servers, please?

best,
Klaus

**Comment by biancode** [comment]
`openapi-generator generate -i https://github.com/mimosa-org/ws-isbm/blob/master/openapi/2.0/isbm_complete.yml -g nodejs-express-server -o Development/test/node-ws-isbm-server > error-openapi-gen.log`

[main] WARN  i.s.parser.util.DeserializationUtils - Error snake-parsing yaml content
io.swagger.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000)
	at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:300)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437)
	at io.swagger.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:137)
	at io.swagger.parser.Swagger20Parser.deserializeYaml(Swagger20Parser.java:83)
	at io.swagger.parser.Swagger20Parser.readWithInfo(Swagger20Parser.java:64)
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:32)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:510)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:560)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:424)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 128, column 34:
        <span style="background-color: #79b8ff;width: 0%;" class="Pro ... 
                                     ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:870)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
	at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:250)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:253)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:87)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
	at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:279)
	... 13 common frames omitted
[main] WARN  i.s.parser.util.DeserializationUtils - Error snake-parsing yaml content
io.swagger.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000)
	at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:300)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437)
	at io.swagger.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:137)
	at io.swagger.parser.Swagger20Parser.deserializeYaml(Swagger20Parser.java:83)
	at io.swagger.parser.Swagger20Parser.readWithInfo(Swagger20Parser.java:64)
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:42)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:510)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:560)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:424)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 128, column 34:
        <span style="background-color: #79b8ff;width: 0%;" class="Pro ... 
                                     ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:870)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
	at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:250)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:253)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:87)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
	at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:279)
	... 13 common frames omitted

**Comment by biancode** [comment]
`openapi-generator generate -i https://raw.githubusercontent.com/mimosa-org/ws-isbm/master/openapi/2.0/isbm_complete.yml -g nodejs-express-server -o /Development/test/node-ws-isbm-server`

[main] WARN  o.o.codegen.utils.ModelUtils - [deprecated] inheritance without use of 'discriminator.propertyName' is deprecated and will be removed in a future release. Generating model for composed schema name: null. Title: null
[main] WARN  o.o.codegen.utils.ModelUtils - [deprecated] inheritance without use of 'discriminator.propertyName' is deprecated and will be removed in a future release. Generating model for composed schema name: null. Title: null
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors:
	-attribute .servers.invalid url : {proto}://{host}:{port}/{basePath}

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:533)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:560)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:424)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

**Comment by biancode** [comment]
fix to get it generated without errors is:

    basePath:
      default: ""

[ws-isbm-openapi-yaml-client.zip](https://github.com/mimosa-org/ws-isbm/files/5212472/ws-isbm-openapi-yaml-client.zip)

**Comment by biancode** [comment]
was a problem with the https://editor.swagger.io/

**Comment by biancode** [comment]
for code generation it could be easier to have version: '2.0.0' instead of just version: '2.0'

**Comment by biancode** [comment]
Node-RED doesn't work with the JSON, too

https://flows.nodered.org/node/openapi-red

![image](https://user-images.githubusercontent.com/4369867/92993353-344d5380-f4f1-11ea-831f-b04816a0e5e7.png)

**Comment by biancode** [comment]
same problem at the official REST JSON

![image](https://user-images.githubusercontent.com/4369867/92993492-4c71a280-f4f2-11ea-9ce3-d7f8ebbe3d88.png)

**Comment by biancode** [comment]
working well in generating was:

`npm i -g oas-generator`
`oas-generator node-ws-isbm-server/api/openapi.yaml -n node-isbm-server`

**Comment by biancode** [comment]
see Node-RED generation from swagger / OPenAPI -- https://medium.com/@kazuhito.yokoi.nx/procedures-to-develop-node-red-node-from-openapi-document-8685fdc7e90a

**Comment by mattys101** [comment]
Thanks for raising this Klaus. The spec was used to generate Java server/client and Ruby server/client using the openapi generator tool, and was also used in the Swagger UI web interface for testing without issue. So it seems the errors are somewhat specific to the generation of NodeJS code.

The original error is pretty easy fixed, so I can put in a default basePath, but bear in mind this is the definition of the specification, while a particular implementation of the specification would likely firm up the definition of the server property.

This also relates to the version numbering, as it is meant to relate to the version of the specification, not an implementation version number. It also means you can use 2.0.0, 2.0.1, etc. where the 3rd value indicates patches or fixes to the implementation rather than any changes in the specification (if that is the way you want to play it).

The error with Node-RED is more difficult since the error the tool is producing seems to provide no useful information to determine where in the specification it is erroring. Unless your last post is indicating that it works if you follow the steps on the linked page?

**Comment by biancode** [comment]
Hi @mattys101, thank you for the answer and information. I posted the link to remember later :)
I'll go further in December or January with Node-RED testing and some implementations.
